# Generated by Django 4.2.7 on 2023-12-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
