# Generated by Django 4.2.7 on 2023-12-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comments_replay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='replay',
            new_name='parent',
        ),
    ]
